#!/bin/bash


set -o nounset
set -o errexit


function main {
    tesseract "$1" /tmp/clitess_out "${@:2}"
    cat /tmp/clitess_out* 2> /dev/null
    rm /tmp/clitess_out* 2> /dev/null
}

function showHelp {
    echo "Tesseract command line tool."
    echo ""
    echo "Display the output of a Tesseract execution without worry of the \
output file"
    echo ""
    echo "Usage:"
    echo "    clitesseract <imagename> [OPTIONS] [CONFIGURATIONS]"
}

if [[ $1 = "--help" || $1 = "-h" ]]; then
    showHelp
else
    main "$@"
fi
