#!/bin/bash

set -o nounset
set -o errexit


# it holds /home/<user>, even if this script is executed with sudo
REAL_USER="$(who -m | awk '{print $1}')"
REAL_HOME="/home/$REAL_USER"


# $1: path of the script
# $2: 1 if it's a script that needs superuser privileges, 0 otherwise
function copyScript {
    scriptBasename=$(basename "$1")
    echo "Copying $scriptBasename"
    cp "$1" "$REAL_HOME/bin"
    chmod 744 "$REAL_HOME/bin/$scriptBasename"
    chgrp "$REAL_USER" "$REAL_HOME/bin/$scriptBasename"
    chown "$REAL_USER" "$REAL_HOME/bin/$scriptBasename"
    if [[ $2 == 1 ]]; then
        # Make a link to /usr/local/sbin, so they are callable with sudo
        ln -svi "$REAL_HOME/bin/$scriptBasename" "/usr/local/sbin/$scriptBasename"
    fi
}


# 1 if the script is executed with sudo, 0 otherwise
SUDO_EXEC="$([[ $(id -u) != 0 ]]; echo $?)"

if [[ $SUDO_EXEC == 0 ]]; then
    echo "WARNING: running this script without sudo \
will not install the scripts that need superuser privileges"
fi

if [[ ! -d "$REAL_HOME/bin" ]] ; then
    echo "Setting up $REAL_HOME/bin"
    mkdir "$REAL_HOME/bin" -m 755
    chgrp "$REAL_USER" "$REAL_HOME/bin"
    chown "$REAL_USER" "$REAL_HOME/bin"
    if ! grep -q 'PATH="\$HOME/bin:\$PATH"' "$REAL_HOME/.profile"; then
        # Add $REAL_HOME/bin folder to the executable path
        {
            echo ""
            echo "# set PATH so it includes user's private bin"
            echo 'if [ -d "$HOME/bin" ] ; then'
            echo '    PATH="$HOME/bin:$PATH"'
            echo 'fi'
        } >> "$REAL_HOME/.profile"

        source "$REAL_HOME/.profile"

        echo "Added $REAL_HOME/bin folder to PATH"
    fi
else
    echo "$REAL_HOME/bin found, assuming that is already in PATH"
fi

# Here add the scripts that must be executed with sudo, separated with spaces
SUDO_SCRIPTS="up set-hyper-threading"

for scriptFile in "$(dirname "$0")"/bin/*; do
    if [[ $SUDO_EXEC == 1 && $SUDO_SCRIPTS == *$(basename "$scriptFile")* ]]; then
        sudoScriptFlag=1
    else
        sudoScriptFlag=0
    fi
    copyScript "$scriptFile" $sudoScriptFlag
done

echo Done
